### ISSUE TITLE
Format clarification

### ISSUE THREAD

**Issue by fbemm** [lh3/gfatools#12]
Dear Heng,

I just have a simple questions regarding the gfa2bed format (when run with -s)

```
Test-2  0       227208972       *       *       *       *       *       *
Test-1       769027  769267  <       Test-2  7108396 <       Test-2  7108066
```

The example tells me that Test-1 (from 769027  769267) is inserted/replacing Test-2 at 7108396 to 7108066.

Am I getting this right?

Thanks!

**Comment by lh3** [comment]
Yes, in the reverse orientation, indicated by `<`.

**Comment by fbemm** [comment]
Thanks!
