### ISSUE TITLE
meaning of NM:i:5 AS:f:56.3 dv:f:0.0694444 id:f:0.930556 cg:Z:4=1X2=1I38=1D5=1I5=1X13=?

### ISSUE THREAD

**Issue by lingliao** [lh3/gfatools#28]
I am trying to figure out the aligned output file .gfa, 

I learned the meaning of these columns
read 71 0 71 + >1>2>4 87 3 73 67 72 60

Please enlighten me what other columns stand for
NM:i:5 AS:f:56.3 dv:f:0.0694444 id:f:0.930556 cg:Z:4=1X2=1I38=1D5=1I5=1X13=

**Comment by lingliao** [comment]
Hello,

Could please sharing how we analysize cg:" Z:4=1X2=1I38=1D5=1I5=1X13="?

Thank you

**Comment by lh3** [comment]
See minigraph manpage.
