### ISSUE TITLE
Online GfaViewer on gfaServer

### ISSUE THREAD

**Issue by hcsun1** [lh3/gfatools#32]
Hello,

I wish I could use your tool 'Online GfaViewer on gfaServer' (https://lh3.github.io/gfatools/) to show the message in GFA file, but I can't find the source code of this tool. Could you please tell me how to find the message?

Thanks for your help.

**Comment by lh3** [comment]
here: https://github.com/lh3/gfatools/tree/master/js

**Comment by lh3** [comment]
Oh, you are probably asking about the gfa-server at pangene.liheng.org? Source code at [here](https://github.com/lh3/gfatools/blob/master/gfa-server.go). Instruction at the [pangene repo](https://github.com/lh3/pangene/#visual).

**Comment by baozg** [comment]
Related question: how should we compile gfa-server? I am using Intel Mac, the linux and arm_mac version are not work for me

**Comment by lh3** [comment]
Install go and run
```sh
make                # compile gfatools
go build gfa-server # compile gfa-server
```

**Comment by baozg** [comment]
Thank you! It worked now with minor change
```
make                # compile gfatools
go build gfa-server.go # compile gfa-server
```
