### ISSUE TITLE
Bug in bubble popping algorithm

### ISSUE THREAD

**Issue by snurk** [lh3/gfatools#5]
Directly copying the description from GFA1 repo [https://github.com/lh3/gfa1/issues/7](url), since it seems to be still there.

I believe there is a bug in bubble popping algorithm that leads to a removal of bubbles with (seemingly arbitrary long) tips of any orientation. See attached gfa (called my.txt to trick github attach dialogue).
[my.txt](https://github.com/lh3/gfatools/files/3817473/my.txt)

Despite looking like this in Bandage it is being simplified into a single unambiguous path by the -b option of gfaview.

![image](https://user-images.githubusercontent.com/988777/68352696-42fafb00-00d5-11ea-85a2-5c3f2a1123d3.png)

**Comment by lh3** [comment]
Bubble popping does some sort of tip trimming at the same time. I have added option `-B` to prevent unintended tip trimming. Note that some command line options of `asm` have been changed. Normally I wouldn't change command line options, but as gfatools is not mature yet, I may make changes occasionally.
